import Head from 'next/head'
import { Heading, Flex, Button, Tag, TagLabel, Text, Box } from '@chakra-ui/react'
import { ChevronDownIcon, ChatIcon, ArrowUpIcon } from '@chakra-ui/icons'
import {
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
} from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import ListItem from '../components/ListItem';

const item = {
  heading: "Can't you just right click?",
  site: "lucasoftware.com",
  time: "10h",
  user: "bangonkeyboard",
  likes: 20,
  comments: 50
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className={styles.main} px={[4, 10]}>
        <Heading as='h1' size='4xl'>
          Hacker <span style={{color: 'teal'}}>news</span>
        </Heading>

        <Flex direction="row" justify='space-between' align='center' width="100%" mt="12">
          <Heading as='h1' size='xl'>
            Top news
          </Heading>
          <Menu>
            <MenuButton as={Button} rightIcon={<ChevronDownIcon />}>
              Actions
            </MenuButton>
            <MenuList>
              <MenuItem>Download</MenuItem>
              <MenuItem>Create a Copy</MenuItem>
              <MenuItem>Mark as Draft</MenuItem>
              <MenuItem>Delete</MenuItem>
              <MenuItem>Attend a Workshop</MenuItem>
            </MenuList>
          </Menu>
        </Flex> 
        <Flex direction="column" width="100%" mt="8">
          <ListItem item={item} />
          <ListItem item={item} />
          <ListItem item={item} />
        </Flex>
      </Box>
    </div>
  )
}
